### ISSUE TITLE
Segfault When Adding Music

### ISSUE THREAD

**Issue by aladar42** [TheWiseNoob/OMP#38]
I have no idea how to debug this, so this is all I know: When I select my entire music folder for additing to the playlist, at some point (seems like at the same point?) the program crashes with this output:

[1]    23619 segmentation fault (core dumped)  omp

I have no idea what file is causing this, becuase I have hundreds of albums, so trying to add them all individually would take forever. So, I have no idea how to supply any more info.

**Comment by aladar42** [comment]
OK, Im dumb and didnt actually have gdb installed. Heres the gdb output:
https://pastebin.com/LmyJMnTR

**Comment by TheWiseNoob** [comment]
Thanks! I'm looking into it now.

**Comment by TheWiseNoob** [comment]
You're using Arch, right? Install OMP again using the omp-git package and try adding your music again. I added some code that will hopefully prevent what's causing the crash with the dynamic cast and some temporary debug code to hopefully show me exactly what file(s) fail when casting.

**Comment by TheWiseNoob** [comment]
Yeah, that should work fine. That didn't work how I hoped. I just committed some debug code that will help us identify exactly what file is causing the issue. Try installing omp again the same way and then look for the last filename that is output. Then you can send me the file causing the issue and I can figure out how to solve the issue without anymore of your help.

**Comment by aladar42** [comment]
Still the same output
Thread 21 "omp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd8f24700 (LWP 17344)]
__cxxabiv1::__dynamic_cast (src_ptr=0x0, 
    src_type=0x7ffff6445848 <typeinfo for TagLib::File>, 
    dst_type=0x7ffff6445510 <typeinfo for TagLib::APE::File>, src2dst=0)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc:50
50	/build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc: No such file or directory.

**Comment by TheWiseNoob** [comment]
I just pushed a new PKGBUILD for omp-git. Try installing and testing it again. That should hopefully force a redownload of the source it acquires via git.

**Comment by TheWiseNoob** [comment]
Hmmm. I'm not sure why nothing is getting output because that dynamic cast only happens at one point and it should be outputting filenames. I'm doubtful, but try compiling it one more time and see if anything outputs. I pushed some new code that should hopefully help figure out the file causing this. Do you have many APE files?

**Comment by aladar42** [comment]
Got some results this time around.

Filename: /run/media/aladar/fad599b8-eb10-4814-95bd-fa0e60942ce7/home/aladar/Music/Death Grips/Death Grips-The Money Store (2012) 24_96 Vinyl FLAC/side A.flac



Filename: /run/media/aladar/fad599b8-eb10-4814-95bd-fa0e60942ce7/home/aladar/Music/Death Grips/Death Grips-The Money Store (2012) 24_96 Vinyl FLAC/side B.flac


Thread 22 "omp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc2ffd700 (LWP 12557)]
__cxxabiv1::__dynamic_cast (src_ptr=0x0, 
    src_type=0x7ffff6444848 <typeinfo for TagLib::File>, 
    dst_type=0x7ffff6444510 <typeinfo for TagLib::APE::File>, src2dst=0)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc:50
50	/build/gcc/src/gcc/libstdc++-v3/libsupc++/dyncast.cc: No such file or directory.

Its a FLAC file with cuesheet. Is that what the problem is?

**Comment by TheWiseNoob** [comment]
No, cue sheets should work fine. Cue sheet parsing support is one of the first features I implemented. Might be a bug in it. Would it be possible for you to send me these files?

**Comment by TheWiseNoob** [comment]
And the error is for an .ape file, so I'm thinking something earlier than I expected is causing the crash. I have an idea for what it might be. Look at the first file alphabetically after those FLAC files and see if it is a .ape file. Then send me that one if possible if it is an APE file.

**Comment by aladar42** [comment]
Nope, the next file is an MP3, I dont think I have any APE files at all on my PC. 
I can send you the file, but its probably around 500+MB, so I would need some way to get it to you

**Comment by aladar42** [comment]
The individual FLAC files work, its the cuesheet that crashes the software. 
I cant access that folder without a Google Account, looks like.

**Comment by TheWiseNoob** [comment]
Yeah, you'll need a Google account to upload anything there. I assumed you probably had one. I can likely figure out the issue using the cuesheet if you want to just upload it to pastebin or something for me, please.

**Comment by aladar42** [comment]
Yeah, here it is https://pastebin.com/gJYsXs1J

**Comment by TheWiseNoob** [comment]
I've solved the crash. There's also one other small bug I want to fix first and then I'll push the commit that fixes this bug. I'll comment here again when it is pushed.

**Comment by TheWiseNoob** [comment]
Will be within 24 hours because I'm too tired to continue right now. Thanks again for your help.

**Comment by TheWiseNoob** [comment]
This multi-file format of cue might also not read properly with OMP. I need to do more testing and make some test files with the same length. All of my multi-file cue sheets work fine, but they have a file for each track and not just two for the whole album. I've never seen a cue sheet like this before. It at least won't crash OMP now. It's a good test case. Thank you.

**Comment by TheWiseNoob** [comment]
I'll post the crash be within 24 hours because I'm too tired to continue right now. Thanks again for your help.

**Comment by TheWiseNoob** [comment]
I just pushed an update that fixes this bug. An unhelpful error will now be output because OMP's cuesheet parser is not designed to handle a cuesheet in that format, but OMP will not crash now. I will be opening another issue for adding support for cuesheet parsing with that format. Thanks for your help!

**Comment by TheWiseNoob** [comment]
Just Opened Issue #39

**Comment by aladar42** [comment]
No probs, glad to help.
Having one audio file per the whole album with a cue sheet having all the splits is actually a very common thing, interesting that you havent come across it yet.

Also, Im getting more errors now, should I open up a new ticket? The most common ones are
-[file] failed to open.
-the mime type is not valid
and
-failed to open with mime type of . (sic)

**Comment by TheWiseNoob** [comment]
OMP does support cuesheets with multiple files and splits in the cue sheet or just a single file with the splits in the cuesheet, just not this dual format that your vinyl rip has. The few vinyl rips I have are split into tracks for each file.

**Comment by TheWiseNoob** [comment]
If OMP isn't crashing, then the errors are just from lack of support. Another Issue would be best, but only if you can provide examples of what is causing the errors.
